blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag')
]

programmer_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('about_me.html/', views.about_me, name='about_me'),
    path('contact_me.html/', views.contact_me, name='contact_me'),
    path('skills.html/', views.skills, name='skills'),
    path('projects.html/', views.projects, name='projects')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()# default manager
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

    tags = TaggableManager()


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    file = models.FileField(upload_to='portfolio/File_uploads', blank=True)

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage,\
    PageNotAnInteger
from django.views.generic import ListView
from .forms import CommentForm
from taggit.models import Tag


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # List of active comments on post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment has been posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # create comment, but dont save to DB
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})


def about_me(request):
    return render(request, 'portfolio/about_me.html')


def contact_me(request):
    return render(request, 'portfolio/contact_me.html')


def skills(request):
    return render(request, 'portfolio/skills.html')


def projects(request):
    return render(request, 'portfolio/projects.html')

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark justify-content-center">
            <li class="nav-item">
                <a href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'about_me' %}">AboutMe</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'contact_me' %}">ContactMe</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'blog:post_list' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'skills' %}">Skills</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'home' %}#projects">Projects</a>
            </li>
        </div>
    </div>


    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>Welcome to my blog, I've written {% total_posts %} posts so far.</p>
        <h3>Latest posts</h3>
        <div class="sidebar-links">
            {% show_latest_posts 3 %}
        </div>
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <div class="detail-page">
        <h1> {{ post.title }}</h1>
        <p class="'date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown }}
        {% with comments.count as total_comments %}
            <h2>{{ total_comments }} comment{{total_comments|pluralize }}</h2>
        {% endwith %}
        {% for comment in comments %}
         <div class="comment">
             <p class="info">
                 Comment {{ forloop.counter }} by {{comment.name}}
                 {{ comment.created }}
             </p>
             {{ comment.body|linebreaks }}
         </div>
        {% empty %}
        <p>There are no comments yet.</p>
        {% endfor %}
        {% if new_comment %}
         <h2>Your comment has been added.</h2>
        {% else %}
         <h2>Add new comment</h2>
         <form method="post">
             {{comment_form.as_p }}
             {% csrf_token %}
             <p><input type="submit" value="Add comment"></p>
         </form>
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/post/latest_posts.html
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>
<ul>
    {% for post in latest_posts %}
    <li>
        <a class="latest-post-link" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

</body>
</html>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <div class="container"></div>
        <div class="list-page">
            <h1>My Blog </h1>
            {% if tag %}
             <h2>Posts tagged with "{{ tag.name }}</h2>
            {% endif %}
            {% for post in posts %}
                <h2>
                    <a class="post-title" href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                        <p class="tags">
                            Tags:
                            {% for tag in post.tags.all %}
                             <a class="tag-list" href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                 {{ tag.name }}
                             </a>
                             {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                    </a>
                </h2>
                <p class="date">
                    Published {{ post.publish }} by {{ post.author }}
                </p>
                {{ post.body|markdown|truncatewords_html:30 }}
            {% endfor %}
          {% include "pagination.html" with page=posts %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/post/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a class="next-page" href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

portfolio/templates/portfolio/about_me.html
<!DOCTYPE html>
{% extends "portfolio/base.html" %}
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}

        <h2 id="about-title">A Little Bit About Me!</h2>
        <div class="container"></div>

            <div class="picture-of-me">

                <img src="{% static 'portfolio/me.jpg' %}" height="500px" width="400px">

            </div>

            <p id="about-me">
                Hello, my name is Tom, software development really appeals to me because I've always enjoyed problem solving,
                I find it to be both mentally stimulating and very rewarding, this is one of the main reasons I decided to
                teach myself to code, that plus I've always enjoyed building things and improving things.
                Whe im not teaching myself to code, my passion for problem solving is reflected in my other main hobby, which is
                bouldering,  which involves figuring out how to climb rocks and walls which might at first look and feel
                impossible. <br>
                Working in the bar industry for about 7 years, mainly in a very busy bar, I got to hone my skills in a very high
                pressure customer oriented environment, having to think on my feet when things around me broke or became
                unavailable.  I also got to apply my skills in a small team of people while opening bars, turning them from a
                building site to a fully working bar, designing glassware plans and back bars, also training staff. <br>
                I decided to teach myself to code when the pandemic hit, as it seemed that the industry i was in was very shaky,
                I planned on only learning python at first, however with me wanting to do things myself, and in order to build this
                portfolio site from scratch, I learnt HTML, CSS, Django and JavaScript along the way, I'm now planning on
                learning much more.
            </p>
        </div>
{% endblock %}


</body>
</html>

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Thomas's Portfolio{% endblock %}</title>
    <link href="{% static 'css/portfolio.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark justify-content-center">
            <li class="nav-item">
                <a href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'about_me' %}">AboutMe</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'contact_me' %}">ContactMe</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'blog:post_list' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'skills' %}">Skills</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'home' %}#projects">Projects</a>
            </li>
        </div>
    </div>
    <div class="my-logo">
        <img src="{% static 'portfolio/logo1.jpg' %}" height="80" width="80">
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>

portfolio/templates/portfolio/contact_me.html
<!DOCTYPE html>
{% extends "portfolio/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container">
    <div class="title">
        <h1>Contact Me</h1>
    </div>
    <div class="details">
        <div class="name">
            <p>Name: Thomas Wasnidge</p>
        </div>
        <div class="email">
            <p>Email Address: thomas.wasnidge@gmail.com</p>
        </div>
        <div class="phone-number">
            <p>Phone Number: 07525644369</p>
        </div>
        <div class="linkedincontact">
            <p>Linked in:</p>
        </div>
    </div>
    <div class="contact-form">
        <p>Alternatively you can contact me directly using the contact form below.</p>
    </div>
</div>

{% endblock %}

</body>
</html>

portfolio/templates/portfolio/home.html
<!DOCTYPE html>
{% extends "portfolio/base.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thomas Wasnidge</title>
</head>
<body>
{% block content %}

    <div class="container">
        <div class="small-info">

            <h4>Blurb</h4>

            <p>Hello, my name is <strong class="my-name">Thomas Wasnidge</strong> and this is my personal website.
            I am a self taught developer, and the idea behind this website is just to show bits of what
            i can do and to let you know a little bit more about me.  It also allows me to track my own progress
            and share bits of what I learn.</p>
        </div>

        <div class="about-this-site">
            <h4>About This Site</h4>
            <p> This site is generated with django, originally I only planned on learning Python, however,
            once I realised that i would need a personal website, learning django to make seemed like the
            obvious route to go down.  This site also incorporates HTML, CSS Bootstrap and JavaScript,
            all of which I picked up along the route to completing this site. </p>


        </div>

        <div class="projects">
            <a name="projects"></a>
            <h2>Personal Projects</h2>
                <div class="container">
                    {% for project in projects %}
                        {% if forloop.first %}<div class="row">{% endif %}
                            <div class="col-lg-4">
                                <div class="project">
                                    <h3>{{project.title}}</h3>
                                    <p>{{project.description}}</p>
                                    <img src = "{{ project.image.url }}" height=200 width = 300>
                                    {% if project.url %}
                                    <br>
                                    <a href="{{project.url}}">{{project.url}}</a>
                                    {% endif %}
                                </div>
                            </div>
                        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                        {% if forloop.last %}</div>{% endif %}
                    {% endfor %}
                </div>
        </div>
            <div class="container">
                <div class="my-links">
                    <div class="row">
                        <div class="col-sm">
                            <div class="git-hub-link">
                                <div class="github-logo">
                                    <img src="{% static 'portfolio/Github.jpg' %}" height="50" width="50">
                                    <a class="github-link" href="https://github.com/wozza0212">My Github Profile</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm">
                            <div class="linked-in-link">
                                <div class="linked-in-logo">
                                    <img src="{% static 'portfolio/linkedin.jpg' %}" height="50" width="50">
                                    <a class="linked-in" href="https://uk.linkedin.com/">LinkedIn</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm">
                            <div class="code-academy-link">
                                <div class="code-academy-logo">
                                    <img src="{% static 'portfolio/codeac1.jpg' %}" height="50" width="50">
                                    <a class="linked-in" href="https://www.codecademy.com/profiles/thomasWasnidge3411926869?next=true">CodeAcademy</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    </div>
{% endblock %}




</body>
</html>

portfolio/templates/portfolio/projects.html
<!DOCTYPE html>
{% extends "portfolio/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>

portfolio/templates/portfolio/skills.html
<!DOCTYPE html>
{% extends "portfolio/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>